name: codecov_ci
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      R_COMPILE_AND_INSTALL_PACKAGES: 'never'
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.3'
    
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        extra-packages: local::. any::covr
          car=?ignore broom=?ignore carData=?ignore colorspace=?ignore
          corrplot=?ignore cpp11=?ignore diffobj=?ignore
          farver=?ignore fotawesome=?ignore fs=?ignore jquerylib=?ignore
          lme4=?ignore nloptr=?ignore quantreg=?ignore
          Rcpp=?ignore RcppEigen=?ignore sass=?ignore SparseM=?ignore
          viridisLite=?ignore
        needs: coverage
    
    - name: Test coverage
      run: covr::codecov(quiet = FALSE)
      shell: Rscript {0}
