name: microdiluteR_ci
on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

env:
  options("install.packages.compile.from.source" = "always")

steps:
- name: Checkout repository
  uses: actions/checkout@v4

- name: Set up R
  uses: r-lib/actions/setup-r@v2
  with:
    r-version: '4.3.3'

- name: Install dependencies
  uses: r-lib/actions/setup-r-dependencies@v2
  with:
    cache-version: 2

- name: Run testthat
  run: Rscript './tests/testthat.R'
