name: R-CI

on:
  push:
    branches:
      - main 

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        R -e 'install.packages("remotes")'
        R -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Run R CMD check
      run: R CMD check .
